"""
PDF to Video - Week 02: Git + Python Fundamentals
"""
import asyncio
import edge_tts
from pathlib import Path
from pdf2image import convert_from_path
from moviepy.editor import ImageClip, AudioFileClip, concatenate_videoclips

PDF_FILE = "week02-git-python.pdf"
OUTPUT_VIDEO = "week02-git-python-lecture.mp4"
VOICE = "th-TH-NiwatNeural"
RATE = "-15%"
DPI = 200

SCRIPTS = [
    # Slide 1 - Title
    """สวัสดีครับนักศึกษาทุกคน...
    ยินดีต้อนรับเข้าสู่ สัปดาห์ที่ 2...
    เรื่อง Git และ Python Fundamentals...
    วันนี้เราจะเรียนพื้นฐานที่สำคัญมาก...
    ทั้ง Version Control และ Python ครับ""",
    
    # Slide 2 - Agenda
    """หัวข้อที่จะเรียนวันนี้ครับ...
    Git Fundamentals พื้นฐาน กิต...
    Python Fundamentals พื้นฐาน ไพธอน...
    Environment Setup การตั้งค่า Environment...
    และ Lab 1 แล็บแรกของเราครับ""",
    
    # Slide 3 - Why Git
    """ทำไมต้องใช้ กิต ครับ...
    กิต เป็น Version Control System...
    ช่วยติดตามการเปลี่ยนแปลงในโค้ด...
    ทำงานร่วมกับคนอื่นได้ง่าย...
    ย้อนกลับไปเวอร์ชันก่อนหน้าได้...
    และสร้าง Branch สำหรับฟีเจอร์ใหม่ได้ครับ""",
    
    # Slide 4 - Git Basic Commands
    """คำสั่ง กิต พื้นฐานครับ...
    git clone ใช้โคลน repository มาที่เครื่อง...
    git status ดูสถานะไฟล์ที่เปลี่ยนแปลง...
    git add . เพิ่มไฟล์ทั้งหมดเข้า staging...
    git commit -m ตามด้วยข้อความ เพื่อบันทึกการเปลี่ยนแปลง...
    git push origin main ส่งขึ้น remote repository ครับ""",
    
    # Slide 5 - Python Data Types
    """มาดู Python Data Types ครับ...
    เราใช้ Type hints เพื่อระบุชนิดข้อมูล...
    str สำหรับข้อความ...
    int สำหรับจำนวนเต็ม...
    float สำหรับทศนิยม...
    bool สำหรับ True False...
    list สำหรับรายการข้อมูล...
    dict สำหรับ key-value pairs ครับ""",
    
    # Slide 6 - Python Classes
    """มาดูการเขียน Python Class ครับ...
    class Document คือการสร้างคลาสใหม่...
    __init__ คือ constructor รับพารามิเตอร์ตอนสร้าง object...
    self.title และ self.content เก็บข้อมูลใน object...
    def get_summary คือ method ที่ return string...
    นี่คือพื้นฐาน OOP ที่จะใช้ตลอดคอร์สครับ""",
    
    # Slide 7 - Conda Environment
    """มาตั้งค่า Conda Environment ครับ...
    conda create -n rag_env python=3.10 -y...
    สร้าง environment ชื่อ rag_env ใช้ Python 3.10...
    conda activate rag_env เพื่อเปิดใช้งาน...
    pip install -r requirements.txt...
    ติดตั้ง libraries ที่จำเป็นทั้งหมดครับ""",
    
    # Slide 8 - Lab 1
    """มาดูแล็บ 1 ครับ... คะแนน 3.75 เปอร์เซ็นต์...
    งานที่ต้องทำมี...
    Fork Generic-RAG repository...
    Clone มาที่เครื่อง...
    สร้าง conda environment...
    สร้าง feature branch...
    เขียน Python OOP ตัวอย่าง...
    แล้ว Commit และ Push...
    เดดไลน์ วันอาทิตย์ 23:59 ครับ""",
    
    # Slide 9 - Questions
    """มีคำถามไหมครับ?...
    แล้วเจอกันในแล็บ 1 นะครับ!...
    อย่าลืมทำให้เสร็จก่อนเดดไลน์ครับ""",
]

async def generate_audio(text, output_file):
    communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
    await communicate.save(output_file)

async def generate_all_audio():
    Path("audio").mkdir(exist_ok=True)
    print("🎤 สร้างเสียง...")
    for i, script in enumerate(SCRIPTS, 1):
        await generate_audio(script, f"audio/slide_{i:02d}.mp3")
        print(f"  ✅ Slide {i}/{len(SCRIPTS)}")

def convert_pdf_to_images():
    Path("images").mkdir(exist_ok=True)
    print("🖼️ แปลง PDF...")
    images = convert_from_path(PDF_FILE, dpi=DPI)
    for i, img in enumerate(images, 1):
        img.save(f"images/slide_{i:02d}.png", "PNG")
    return len(images)

def create_video(num_slides):
    print("🎬 สร้างวีดีโอ...")
    clips = []
    for i in range(1, num_slides + 1):
        img, aud = f"images/slide_{i:02d}.png", f"audio/slide_{i:02d}.mp3"
        if Path(aud).exists():
            audio = AudioFileClip(aud)
            clip = ImageClip(img).set_duration(audio.duration).set_audio(audio)
        else:
            clip = ImageClip(img).set_duration(5)
        clips.append(clip)
    final = concatenate_videoclips(clips, method="compose")
    final.write_videofile(OUTPUT_VIDEO, fps=24, codec="libx264", audio_codec="aac", verbose=False, logger=None)
    final.close()
    print(f"✅ {OUTPUT_VIDEO}")

async def main():
    print(f"🎬 Week 02: Git + Python Fundamentals")
    if not Path(PDF_FILE).exists():
        print(f"❌ ไม่พบ {PDF_FILE}")
        return
    await generate_all_audio()
    num = convert_pdf_to_images()
    create_video(min(num, len(SCRIPTS)))

if __name__ == "__main__":
    asyncio.run(main())
