"""
PDF to Video - Week 09: CI/CD
"""
import asyncio
import edge_tts
from pathlib import Path
from pdf2image import convert_from_path
from moviepy.editor import ImageClip, AudioFileClip, concatenate_videoclips

PDF_FILE = "week09-cicd.pdf"
OUTPUT_VIDEO = "week09-cicd-lecture.mp4"
VOICE = "th-TH-NiwatNeural"
RATE = "-15%"
DPI = 200

SCRIPTS = [
    """สวัสดีครับ สัปดาห์ที่ 9 เรื่อง CI/CD...
    สัปดาห์สุดท้ายของการเรียน!...
    วันนี้เราจะเรียนรู้การทำ Automation...
    สำหรับ Build Test และ Deploy ครับ""",
    
    """หัวข้อวันนี้ครับ...
    CI/CD คืออะไร...
    pytest Testing...
    GitHub Actions...
    Jenkins...
    และ Lab 8 ครับ""",
    
    """CI/CD คืออะไรครับ...
    CI ย่อมาจาก Continuous Integration...
    Build และ Test อัตโนมัติทุกครั้งที่ Push โค้ด...
    CD ย่อมาจาก Continuous Deployment...
    Deploy อัตโนมัติเมื่อ Test ผ่านครับ""",
    
    """ทำไมต้อง CI/CD ครับ...
    ลดความผิดพลาดจากคน...
    ได้ Feedback รวดเร็ว...
    Deploy ได้บ่อยและปลอดภัย...
    ทีมทำงานได้มีประสิทธิภาพมากขึ้นครับ""",
    
    """pytest คืออะไรครับ...
    Framework สำหรับเขียน Test ใน Python...
    เขียนง่าย อ่านง่าย...
    รัน Test อัตโนมัติ...
    สร้าง Coverage Report ได้ครับ""",
    
    """การเขียน Test ครับ...
    สร้างไฟล์ test_*.py...
    สร้าง function def test_*...
    ใช้ assert ตรวจสอบผลลัพธ์...
    รันด้วยคำสั่ง pytest ครับ""",
    
    """GitHub Actions ครับ...
    CI/CD ที่ built-in มากับ GitHub...
    กำหนด Workflow ในไฟล์ YAML...
    Trigger เมื่อ Push หรือ Pull Request...
    รันบน GitHub Servers ฟรีครับ""",
    
    """Jenkins ครับ...
    CI/CD Server ที่ยืดหยุ่นมาก...
    Self-hosted รันที่เครื่องเราเอง...
    มี Plugins มากมาย...
    เหมาะสำหรับองค์กรขนาดใหญ่ครับ""",
    
    """Pipeline ครับ...
    Push โค้ดขึ้น GitHub...
    Trigger CI/CD Pipeline...
    Build Docker Images...
    Run Tests...
    Deploy ถ้า Test ผ่านครับ""",
    
    """Lab 8 ครับ คะแนน 3.75 เปอร์เซ็นต์...
    เขียน pytest Tests...
    สร้าง GitHub Actions Workflow...
    สร้าง Jenkinsfile...
    ทดสอบ Pipeline...
    เดดไลน์ วันอาทิตย์ 23:59 ครับ""",
    
    """ยินดีด้วยครับ!...
    ทุกคนผ่านมาครบทั้ง 9 สัปดาห์ และ 8 Labs!...
    ตอนนี้พร้อมทำ Project Phase แล้ว...
    ขอบคุณที่ตั้งใจเรียนตลอดเทอมครับ!""",
]

async def generate_audio(text, output_file):
    communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
    await communicate.save(output_file)

async def generate_all_audio():
    Path("audio").mkdir(exist_ok=True)
    print("🎤 สร้างเสียง...")
    for i, script in enumerate(SCRIPTS, 1):
        await generate_audio(script, f"audio/slide_{i:02d}.mp3")
        print(f"  ✅ Slide {i}/{len(SCRIPTS)}")

def convert_pdf_to_images():
    Path("images").mkdir(exist_ok=True)
    print("🖼️ แปลง PDF...")
    images = convert_from_path(PDF_FILE, dpi=DPI)
    for i, img in enumerate(images, 1):
        img.save(f"images/slide_{i:02d}.png", "PNG")
    return len(images)

def create_video(num_slides):
    print("🎬 สร้างวีดีโอ...")
    clips = []
    for i in range(1, num_slides + 1):
        img, aud = f"images/slide_{i:02d}.png", f"audio/slide_{i:02d}.mp3"
        if Path(aud).exists():
            audio = AudioFileClip(aud)
            clip = ImageClip(img).set_duration(audio.duration).set_audio(audio)
        else:
            clip = ImageClip(img).set_duration(5)
        clips.append(clip)
    final = concatenate_videoclips(clips, method="compose")
    final.write_videofile(OUTPUT_VIDEO, fps=24, codec="libx264", audio_codec="aac", verbose=False, logger=None)
    final.close()
    print(f"✅ {OUTPUT_VIDEO}")

async def main():
    print(f"🎬 Week 09: CI/CD")
    if not Path(PDF_FILE).exists():
        print(f"❌ ไม่พบ {PDF_FILE}")
        return
    await generate_all_audio()
    num = convert_pdf_to_images()
    create_video(min(num, len(SCRIPTS)))

if __name__ == "__main__":
    asyncio.run(main())
