"""
PDF to Video - Week 08: Docker Compose
"""
import asyncio
import edge_tts
from pathlib import Path
from pdf2image import convert_from_path
from moviepy.editor import ImageClip, AudioFileClip, concatenate_videoclips

PDF_FILE = "week08-docker-compose.pdf"
OUTPUT_VIDEO = "week08-docker-compose-lecture.mp4"
VOICE = "th-TH-NiwatNeural"
RATE = "-15%"
DPI = 200

SCRIPTS = [
    """สวัสดีครับ สัปดาห์ที่ 8 เรื่อง Docker Compose...
    วันนี้เราจะเรียนรู้การรันหลาย Services พร้อมกัน...
    ด้วย Docker Compose ครับ""",
    
    """หัวข้อวันนี้ครับ...
    Docker Compose คืออะไร...
    docker-compose.yml...
    Multi-container Applications...
    และ Lab 7 ครับ""",
    
    """Docker Compose คืออะไรครับ...
    เครื่องมือสำหรับรันหลาย Containers พร้อมกัน...
    กำหนดทุกอย่างในไฟล์ YAML เดียว...
    สั่งรันด้วยคำสั่งเดียว...
    เหมาะสำหรับ Application ที่มีหลาย Services ครับ""",
    
    """docker-compose.yml ครับ...
    กำหนด Services ที่ต้องการ...
    ระบุ Image หรือ Build context...
    กำหนด Ports ที่เปิด...
    ตั้งค่า Environment variables...
    กำหนด Dependencies ระหว่าง Services ครับ""",
    
    """Advanced-RAG-Docker ครับ...
    มี 6 Services...
    OpenSearch สำหรับ Vector Database...
    Embedding Service สร้าง Embeddings...
    Search API สำหรับค้นหา...
    Backend API สำหรับ RAG...
    Frontend Streamlit UI...
    และ Ollama สำหรับ LLM ครับ""",
    
    """Docker Network ครับ...
    Services สื่อสารกันผ่าน Docker Network...
    ใช้ชื่อ Service เป็น hostname...
    ไม่ต้อง hardcode IP Address...
    ปลอดภัยและยืดหยุ่นครับ""",
    
    """คำสั่งที่ใช้บ่อยครับ...
    docker-compose up -d รัน Services...
    docker-compose ps ดู Status...
    docker-compose logs ดู Logs...
    docker-compose down หยุด Services...
    docker-compose down -v ลบ Volumes ด้วยครับ""",
    
    """Lab 7 ครับ คะแนน 3.75 เปอร์เซ็นต์...
    Clone Advanced-RAG-Docker...
    ศึกษา docker-compose.yml...
    รัน 6 Services...
    ทดสอบ Application...
    เดดไลน์ วันอาทิตย์ 23:59 ครับ""",
    
    """มีคำถามไหมครับ?...
    แล็บนี้สนุก ได้เห็นระบบ RAG ครบวงจรทำงานจริง!...
    แล้วเจอกันในแล็บ 7 นะครับ!""",
]

async def generate_audio(text, output_file):
    communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
    await communicate.save(output_file)

async def generate_all_audio():
    Path("audio").mkdir(exist_ok=True)
    print("🎤 สร้างเสียง...")
    for i, script in enumerate(SCRIPTS, 1):
        await generate_audio(script, f"audio/slide_{i:02d}.mp3")
        print(f"  ✅ Slide {i}/{len(SCRIPTS)}")

def convert_pdf_to_images():
    Path("images").mkdir(exist_ok=True)
    print("🖼️ แปลง PDF...")
    images = convert_from_path(PDF_FILE, dpi=DPI)
    for i, img in enumerate(images, 1):
        img.save(f"images/slide_{i:02d}.png", "PNG")
    return len(images)

def create_video(num_slides):
    print("🎬 สร้างวีดีโอ...")
    clips = []
    for i in range(1, num_slides + 1):
        img, aud = f"images/slide_{i:02d}.png", f"audio/slide_{i:02d}.mp3"
        if Path(aud).exists():
            audio = AudioFileClip(aud)
            clip = ImageClip(img).set_duration(audio.duration).set_audio(audio)
        else:
            clip = ImageClip(img).set_duration(5)
        clips.append(clip)
    final = concatenate_videoclips(clips, method="compose")
    final.write_videofile(OUTPUT_VIDEO, fps=24, codec="libx264", audio_codec="aac", verbose=False, logger=None)
    final.close()
    print(f"✅ {OUTPUT_VIDEO}")

async def main():
    print(f"🎬 Week 08: Docker Compose")
    if not Path(PDF_FILE).exists():
        print(f"❌ ไม่พบ {PDF_FILE}")
        return
    await generate_all_audio()
    num = convert_pdf_to_images()
    create_video(min(num, len(SCRIPTS)))

if __name__ == "__main__":
    asyncio.run(main())
