"""
PDF to Video - Lab 08: CI/CD + Testing
"""
import asyncio
import edge_tts
from pathlib import Path
from pdf2image import convert_from_path
from moviepy.editor import ImageClip, AudioFileClip, concatenate_videoclips

PDF_FILE = "lab08.pdf"
OUTPUT_VIDEO = "lab08-cicd-testing.mp4"
VOICE = "th-TH-NiwatNeural"
RATE = "-15%"
DPI = 200

SCRIPTS = [
    """สวัสดีครับ... แล็บที่ 8 เรื่อง CI/CD และ เทสติ้ง...
    คะแนน 3.75 เปอร์เซ็นต์ครับ... แล็บสุดท้ายแล้ว!...
    เราจะเรียนรู้การเขียนเทสต์ และสร้าง CI/CD ไปป์ไลน์""",
    
    """วัตถุประสงค์ครับ...
    เขียน pytest เทสต์...
    สร้าง CI/CD ไปป์ไลน์...
    และตั้งค่า GitHub Actions ครับ""",
    
    """ทาสค์แรก... เขียน test_api.py ครับ...
    อิมพอร์ต pytest และ TestClient จาก fastapi...
    สร้าง client จาก app...
    เขียน test_health เช็ค status code 200...
    เขียน test_search เช็ค POST /search ครับ...
    เทสต์ช่วยให้เรามั่นใจว่าโค้ดทำงานถูกต้อง""",
    
    """ทาสค์ที่ 2... รันเทสต์ครับ...
    พิมพ์ pytest tests/ -v เพื่อรันแบบ verbose...
    หรือ pytest tests/ --cov=. --cov-report=html...
    เพื่อดู coverage report ว่าเทสต์ครอบคลุมโค้ดแค่ไหน...
    coverage report ช่วยหาส่วนที่ยังไม่ได้เทสต์ครับ""",
    
    """ทาสค์ที่ 3... สร้าง Jenkinsfile ครับ...
    Jenkinsfile กำหนด ไปป์ไลน์ CI/CD...
    มี 3 stages... Build, Test, Deploy...
    stage Build รัน docker-compose build...
    stage Test รัน pytest...
    stage Deploy รัน docker-compose up -d ครับ""",
    
    """ทาสค์ที่ 4... สร้าง GitHub Actions ครับ...
    สร้างไฟล์ .github/workflows/ci.yml...
    กำหนด trigger เมื่อ push หรือ pull request...
    ให้รันบน ubuntu-latest...
    steps มี checkout, build, up, wait, health check ครับ""",
    
    """ภาพรวม CI/CD ไปป์ไลน์ครับ...
    Push โค้ดขึ้น GitHub...
    ไปป์ไลน์ เริ่ม Build อัตโนมัติ...
    รัน Test อัตโนมัติ...
    ถ้าผ่านก็ Deploy อัตโนมัติ...
    ทำให้การ ดีพลอย รวดเร็ว และลดความผิดพลาดจากคนครับ""",
    
    """สิ่งที่ต้องส่งครับ...
    เขียนเทสต์แล้ว... เทสต์ผ่านทั้งหมด...
    สร้าง Jenkinsfile แล้ว...
    สร้าง GitHub Actions workflow แล้ว...
    พร้อมเอกสารอธิบาย...
    เดดไลน์ วันอาทิตย์ 23:59 ครับ!...
    ยินดีด้วยที่ผ่านมาครบทั้ง 8 แล็บ!""",
]

async def generate_audio(text, output_file):
    communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
    await communicate.save(output_file)

async def generate_all_audio():
    Path("audio").mkdir(exist_ok=True)
    print("🎤 สร้างเสียง...")
    for i, script in enumerate(SCRIPTS, 1):
        await generate_audio(script, f"audio/slide_{i:02d}.mp3")
        print(f"  ✅ Slide {i}/{len(SCRIPTS)}")

def convert_pdf_to_images():
    Path("images").mkdir(exist_ok=True)
    print("🖼️ แปลง PDF...")
    images = convert_from_path(PDF_FILE, dpi=DPI)
    for i, img in enumerate(images, 1):
        img.save(f"images/slide_{i:02d}.png", "PNG")
    return len(images)

def create_video(num_slides):
    print("🎬 สร้างวีดีโอ...")
    clips = []
    for i in range(1, num_slides + 1):
        img, aud = f"images/slide_{i:02d}.png", f"audio/slide_{i:02d}.mp3"
        if Path(aud).exists():
            audio = AudioFileClip(aud)
            clip = ImageClip(img).set_duration(audio.duration).set_audio(audio)
        else:
            clip = ImageClip(img).set_duration(5)
        clips.append(clip)
    final = concatenate_videoclips(clips, method="compose")
    final.write_videofile(OUTPUT_VIDEO, fps=24, codec="libx264", audio_codec="aac", verbose=False, logger=None)
    final.close()
    print(f"✅ {OUTPUT_VIDEO}")

async def main():
    print(f"🎬 Lab 08: CI/CD + Testing")
    if not Path(PDF_FILE).exists():
        print(f"❌ ไม่พบ {PDF_FILE}")
        return
    await generate_all_audio()
    num = convert_pdf_to_images()
    create_video(min(num, len(SCRIPTS)))

if __name__ == "__main__":
    asyncio.run(main())
